In [7]:
import os
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs
from myfunc import text_clean

In [8]:
url="https://www.yes24.com/product/category/bestseller"
payload = dict(categoryNumber="001", pageNumber=1, pageSize=24)
r = requests.get(url, params = payload)
soup = bs(r.content, "lxml")
soup

<!DOCTYPE html>
<html lang="ko">
<head><link href="https://m.yes24.com/Home/Best?DispNo=001" media="only screen and(max-width: 640px)" rel="alternate"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
<meta content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" http-equiv="Accept-CH"/>
<meta content="86400" http-equiv="Accept-CH-Lifetime"/>
<meta content="unsafe-url" name="referrer"/>
<meta content="width=1170" name="viewport"/>
<title> 국내도서 종합 베스트 - 예스24 </title>
<meta content="예스24" name="title"/>
<meta content="도서, 티켓, 음반, 굿즈, 커뮤니티까지 문화 전반을 아우르는 국내 대표 문화콘텐츠 플랫폼, 아낌없는 혜택과 총알배송을 경험해보세요." name="description"/>
<meta content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" name="keywords"/>
<link href="//www.yes24.com/OpensearchDescription.xml" rel="search" title="YES24" type="application/opensearchdescription+xml"/>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/util.js?v=20251114_a" type="text/javascript"></script>
<script charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20250618" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/jqueryExtendsPC.min.js?v=20250618" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250613" type="text/javascript"></script>
<script src="https://www.yes24.com/Javascript/Search/bulletSearch.js?v=20260107" type="text/javascript"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20251201" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSiteList.min.js?v=20251111_1" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/RedirectWebSite.min.js?v=20251111_1" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/static/common/frontCommon.js?v=20260205_b" type="text/javascript"></script>
<script charset="UTF-8" src="https://image.yes24.com/static/common/addon.js?v=20260204" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20250613" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20251111_1" type="text/javascript"></script>
<link charset="euc-kr" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20260113" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20251208" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20260205" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20250818" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20250818" rel="stylesheet" type="text/css"/>
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20250818" />
	<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);
		// 브레이즈 위한 설정 값
		var TUSERNO = '';
		var isUnder14 = 'False';

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
<script src="https://www.yes24.com/javascript/common.js?v=20260205_b" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250916" type="text/javascript"></script>
<script src="https://image.yes24.com/static/logging/clickstream.min.js?v=20250709" type="text/javascript"></script>
<script src="https://image.yes24.com/static/logging/brazeSDK.js?v=20260210" type="text/javascript"></script>
<script defer="" src="https://image.yes24.com/static/logging/brazeHelper.js?v=20260210" type="text/javascript"></script>
<script src="https://image.yes24.com/static/logging/airbridgeSDK.js?v=20260210"></script>
<script src="https://image.yes24.com/static/logging/airbridgeHelper.js?v=20260210"></script>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager -->
<script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
<!-- End Google Tag Manager -->
<script async="" src="https://cdn.onetag.co.kr/0/tcs.js?eid=skxx6fnq6ueeskxx6fnq6u"></script>
<link href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20260224" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?ver=20251022" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/best/best.css?ver=20250818" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/yesLocation.css?ver=20250818" media="all" rel="stylesheet" type="text/css"/></head>
<body>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
<dt>콘텐츠 바로가기</dt>
<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>
<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div class="" id="yesWrap">
<div id="yesHeaderArea" style="">
<!-- ########## TOPBANNER 영역 시작 ########## -->
<section>
<div id="upperBnWrap" style="display:none;">
<div id="upperBnRoll">
<div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#f5f5ce"><a href="https://event.yes24.com/onlyApp" onclick="setWcode('001');"><img alt="도서앱" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_01.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#f7cce3"><a href="https://event.yes24.com/present?eventNo=267385" onclick="setWcode('001');"><img alt="폴더블독서등" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_01.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#c3e3f6"><a href="https://event.yes24.com/yesBenefit" onclick="setWcode('001');"><img alt="3월혜택" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_02.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#c6f1cc"><a href="https://event.yes24.com/present?eventNo=267385" onclick="setWcode('001');"><img alt="쿠션방석" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_02.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#fbf7df"><a href="https://event.yes24.com/detail?eventNo=267829" onclick="setWcode('001');"><img alt="젊은시인" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_L_03.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#f4d29d"><a href="https://event.yes24.com/present?eventNo=267385" onclick="setWcode('001');"><img alt="폴더블독서등" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2026/0311_topbn_480x50_R_03.png" width="480"/></a></div>
</div>
</div>
</div>
<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
</div>
</section>
<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
<!-- ########## TOPBANNER 영역 끝 ########## -->
<!-- ########## HEADER 영역 시작 ########## -->
<div id="yHeader">
<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onclick="setWcode('001_004');"><svg aria-label="YES24" role="img" type="image/svg+xml"><image alt="YES24" height="103" src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" width="200" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" xmlns:xlink="http://www.w3.org/1999/xlink"/></svg></a></h1>
<div id="yHeaderWrap">
<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
<div class="yHeaderTop">
<h2 class="yBlind">YES24 카테고리 리스트</h2>
<ul class="cateLi" id="ulCategoryList"><li class="cate001 cateOn"><a href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" title="국내도서"><em class="txt">국내도서</em></a></li><li class="cate002"><a href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002" onclick="setWcode('001_002_002')" title="외국도서"><em class="txt">외국도서</em></a></li><li class="cate018"><a href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" title="중고샵"><em class="txt">중고샵</em></a></li><li class="cate017"><a href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')" title="eBook"><em class="txt">eBook</em></a></li><li class="cateCrC"><a href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')" title="크레마클럽"><em class="txt">크레마클럽</em></a></li><li class="cate003"><a href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" title="CD/LP"><em class="txt">CD/LP</em></a></li><li class="cate004"><a href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" title="DVD/Blu-ray"><em class="txt">DVD/BD</em></a></li><li class="cate006"><a href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" title="GIFT"><em class="txt"><u>문구</u>/GIFT</em></a></li><li class="cateENT"><a href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank" title="티켓"><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
<h2 class="yBlind">YES24 유틸메뉴</h2>
<ul class="utilLi">
<li id="LoginText">
<input id="hdfLoginYn" type="hidden" value="N"/>
<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>
</li>
<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>
<li class="myPgGrp">
<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
<dl class="myPgDl">
<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
<dd>
<ul>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
</ul>
</dd>
</dl>
</li>
<li><a href="https://ssl.yes24.com/Cart/Cart" onclick="setWcode('001_003_010')"><em class="txt">카트</em></a></li>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_011')"><em class="txt">주문/배송</em></a></li>
<li class="lastLi"><a href="https://www.yes24.com/Templates/FTCusMain.aspx?Wcode=001_003_012" onclick="setWcode('001_003_012')"><em class="txt">고객센터</em></a></li>
</ul>
<dl class="globalYesInfoDl">
<dt><a href="javascript:void(0);"><em class="txt">Global YES24</em><em class="ico_arr bgGNB">안내보기</em></a></dt>
<dd>
<div class="globalYesInfoContArea">
<div class="globalYesInfoCont">
<p class="yesInfo_tit">Global YES24는?</p>
<p class="yesInfo_des">
									K-POP/K-Drama 관련상품(음반,도서,DVD)을<br/> 영문/중문 으로 이용하실 수 있습니다.
								</p>
<div class="yesInfo_globalTxt">
<p class="globalTxt_des">
										Korean wave shopping mall, sell the <br/>K-POP/K-Drama (CD,DVD,Blu-ray,Book)
										We aceept PayPal/UnionPay/Alipay<br/> and support English/Chinese Language service
									</p>
<a class="btnC btn_blue" href="https://global.yes24.com" onclick="setWcode('001_016_002')" target="_blank"><span class="bWrap"><em class="txt">English</em></span></a>
<p class="globalTxt_des">
									 作为出售正规 K-POP/K-Drama 相关(CD,图书,DVD) 韩流商品的网站, 支持 中文/英文 等海外结账方式
									</p>
<a class="btnC btn_blue" href="https://cn.yes24.com" onclick="setWcode('001_016_003')" target="_blank"><span class="bWrap"><em class="txt">中文</em></span></a>
<p class="globalTxt_des">
									 Exclusive ticket sales for domestic and international pop artists
									</p>
<a class="btnC btn_blue" href="http://ticket.yes24.com/English?Gcode=009_205" onclick="setWcode('001_016_004')" target="_blank"><span class="bWrap"><em class="txt">Global yesticket</em></span></a>
</div>
</div>
</div>
</dd>
</dl>
</div>
<!-- %%%%%%%%%% 해더 Top 영역 끝 %%%%%%%%%% -->
<hr/>
<!-- %%%%%%%%%% 해더 Mid 영역 시작 %%%%%%%%%% -->
<div class="yHeaderMid">
<div class="yesSearch">
<form accept-charset="utf-8" action="//www.yes24.com/product/search?" id="yesSForm" method="get" name="HeadForm" onsubmit="return check_search();">
<input id="keywordAd" name="keywordAd" type="hidden" value=""/>
<input id="keyword" name="keyword" type="hidden"/>
<input id="domain" name="domain" type="hidden" value="ALL"/>
<input id="qdomain" name="qdomain" type="hidden" value="전체"/>
<fieldset>
<legend>검색</legend>
<span class="schIpt">
<label><input accesskey="s" autocomplete="off" class="iptTxt" id="query" maxlength="80" name="query" onblur="blurSearchBar();" onfocus="showLatestSearchList();" onkeydown="SearchBarRenderingEnableSet(false);init_searchbox();" onmousedown="SearchBarRenderingEnableSet(false);Common_init_searchbox();" style="ime-mode: active;" title="YES24 검색어 입력" type="text" value=""/></label>
</span>
<div style="position:absolute;top:-1000em;left:0;width:1px;height:1px;overflow:hidden;">
<script charset="euc-kr" src="//adgirl.yes24.com/RealMedia/ads/adstream_mjx.ads/www.yes24.com/Header/SearchBar@x01" type="text/javascript"></script>
<script type="text/javascript">
							try {
								OAS_RICH("x01");
							} catch (e) { }
						</script>
</div>
<script type="text/javascript">
						var url = location.href;
						var reUrl = url.toLowerCase();

						$(document).ready(function () {
							//검색결과
						    if (reUrl.indexOf('/product/search') > -1 && reUrl.indexOf('/product/search/searchkeyword') <= 0) {
								SearchBarRenderingEnable = false;

								if (getParamValue("query") != undefined) {
									$("#query").val($("#hidSearchWord").val());
									fnGetValueDomain($("#hidSearchDomain").val());
									$("#domain").val($("#hidSearchDomain").val());
									$("#qdomain").val($("#hidSearchQdomain").val());
								}
							}
							if (SearchBarRenderingEnable == true) {
								fnSearchBarRendering();
							}
						});

						// 검색어 입력창에 포커스 시
						function SearchBarRenderingEnableSet(enable) {
							//광고 제거
							SearchBarRenderingEnable = enable;
							$("#ulSchScopeOpt").hide();
						}

						// 검색어 입력창 광고 노출
						function fnSearchBarRendering() {
							var seardtext = $('#hdSearchBarText').val();
							var bannerLink = $("#hdSearchBarLink").val();

							$('#query').val(seardtext);
							$('#query').addClass("iptTxt iptTxtAd");
							$('#keywordAd').val(bannerLink);
						}

						//검색창 선택 시
						function showLatestSearchList() {
							SearchBarRenderingEnableSet(false);
							if (String($("input#query").val()).length == 0) {
								try{
									srchHistory.show();
								}catch(e){}
								$("#suggestSearchList").hide();
								$("#searchKeyLayer").show();
								$("#latestSearchList").show();
							} else {
								BulletSearchRenewal.InitBulletSearch();
								showSuggestSearchList();
							}
						}

						//검색창 포커스 아웃
						function blurSearchBar() {
							var queryValue = $("#query").val();

# 종류, 책 제목, 상세페이지 링크, 저자/역/글그림/그림, 출판사, 출간일, 가격, 회원리뷰수, 평점

In [10]:
result={}
for item in soup.select("#yesBestList > li"):
    
    book_id=item.select_one(".gd_name")["href"].split("/")[-1]

    # 책 종류
    kind=text_clean(item.select_one(".gd_res").get_text())

    # 책 제목
    book_title=item.select_one(".gd_name").get_text()

    # 상세페이지 링크
    detail_link="https://www.yes24.com" + item.select_one(".gd_name")["href"]

    # 저자/역자
    author=item.select_one(".authPub.info_auth").get_text().replace("\n", "").replace("\r", "")

    # 출판사
    publisher=item.select_one(".authPub.info_pub").get_text()

    # 출간일
    pub_date=item.select_one(".authPub.info_date").get_text()

    # 가격
    book_price=int(item.select_one("div.info_row.info_price em.yes_b").get_text().replace(",",""))

    # 리뷰수
    n_reviews=int(item.select_one(".txC_blue").get_text().replace(",","")) if item.select_one(".txC_blue") != None else 0

    # 리뷰 평점
    rating=float(item.select_one(".rating_grade em.yes_b").get_text()) if item.select_one(".rating_grade em.yes_b") != None else 0

    keys=("book_id", "kind","book_title","detail_link","author","publisher","pub_date","book_price","n_reviews","rating")
    
    values=(book_id, kind,book_title,detail_link,author,publisher,pub_date,book_price,n_reviews,rating)
    
    for key,value in zip(keys, values):
        result.setdefault(key, []).append(value)

df=pd.DataFrame(result)
df

,book_id,kind,book_title,detail_link,author,publisher,pub_date,book_price,n_reviews,rating
0,164510819,도서,괴테는 모든 것을 말했다,https://www.yes24.com/product/goods/164510819,스즈키 유이 저/이지수 역,리프,2025년 11월,15300,321,9.0
1,177044720,도서,인생을 위한 최소한의 생각,https://www.yes24.com/product/goods/177044720,"신영준, 고영성 저",상상스퀘어,2026년 02월,17820,31,9.2
2,180975910,도서,인생 마지막에 쓰는 주식투자 교과서,https://www.yes24.com/product/goods/180975910,정규준 저,애덤스미스,2026년 03월,22500,19,9.9
3,180137091,도서,완벽한 원시인,https://www.yes24.com/product/goods/180137091,자청 저,필로틱,2026년 03월,19800,72,9.4
4,173082175,도서,나의 완벽한 장례식,https://www.yes24.com/product/goods/173082175,조현선 저,북로망스,2026년 01월,17100,110,9.5
5,101375755,도서,프로젝트 헤일메리 (영화 특별판),https://www.yes24.com/product/goods/101375755,앤디 위어 저/강동혁 역,알에이치코리아(RHK),2026년 02월,19800,813,9.7
6,167466420,도서,"2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상",https://www.yes24.com/product/goods/167466420,최태성 저,이투스북,2025년 12월,17100,64,9.9
7,168226997,도서,진보를 위한 주식투자,https://www.yes24.com/product/goods/168226997,이광수 저,21세기북스,2025년 12월,19800,172,8.9
8,167466432,도서,"2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하",https://www.yes24.com/product/goods/167466432,최태성 저,이투스북,2025년 12월,16650,46,10.0
9,149385533,도서,자몽살구클럽,https://www.yes24.com/product/goods/149385533,한로로 저,어센틱,2025년 07월,10800,213,9.2
10,176913274,도서,부처님 말씀대로 살아보니,https://www.yes24.com/product/goods/176913274,토니 페르난도 저/강정선 역,윌마,2026년 02월,17010,57,9.9
11,168776448,도서,ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC,https://www.yes24.com/product/goods/168776448,ETS 저,YBM(와이비엠),2025년 12월,19800,81,9.9
12,8759796,도서,모순,https://www.yes24.com/product/goods/8759796,양귀자 저,쓰다,2013년 04월,11700,1971,9.6
13,180510407,도서,다있소 과학 1,https://www.yes24.com/product/goods/180510407,윤자영 글/노이신 그림,다른어린이,2026년 03월,13050,49,10.0
14,148032819,도서,박곰희 연금 부자 수업,https://www.yes24.com/product/goods/148032819,박곰희 저,인플루엔셜,2025년 06월,18900,376,9.7
15,166577463,도서,죽은 왕녀를 위한 파반느 (양장 특별판),https://www.yes24.com/product/goods/166577463,박민규 저,위즈덤하우스,2025년 11월,18000,114,9.4
16,27582352,도서,엄마가 유령이 되었어!,https://www.yes24.com/product/goods/27582352,노부미 글그림/이기웅 역,길벗어린이,2016년 05월,10800,85,8.8
17,168776455,도서,ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC,https://www.yes24.com/product/goods/168776455,ETS 저,YBM(와이비엠),2025년 12월,19800,79,9.9
18,182425073,만화,슈퍼 뒤에서 담배 피우는 두 사람 7 특별판,https://www.yes24.com/product/goods/182425073,지누시 글그림/김성래 역,디앤씨미디어(D&C미디어),2026년 03월,18000,4,10.0
19,182234372,만화,스파이 패밀리 Spy Family 16,https://www.yes24.com/product/goods/182234372,엔도 타츠야 글그림,학산문화사,2026년 03월,5400,16,9.6
20,67362730,도서,해커스 토익 기출 VOCA (보카),https://www.yes24.com/product/goods/67362730,David Cho 저,해커스어학연구소,2024년 08월,11610,1208,9.6
21,147276346,도서,너를 아끼며 살아라,https://www.yes24.com/product/goods/147276346,나태주 저,더블북,2025년 06월,16650,146,9.8
22,169902356,도서,캔들차트 하나로 끝내는 추세추종 투자,https://www.yes24.com/product/goods/169902356,성승현 저,포르체,2026년 01월,22500,49,9.0
23,257435,도서,싯다르타,https://www.yes24.com/product/goods/257435,헤르만 헤세 저/박병덕 역,민음사,2002년 01월,7200,702,9.5

# 저자 분리하기

In [11]:
author_result = []
for item in soup.select("#yesBestList > li"):
    result = {} # 1권의 저자 정보가 모임
    authors = item.select_one(".authPub.info_auth").get_text()
    if "보기/감추기" in authors:
        temp = authors.split("보기/감추기")
        author = temp[1].strip().split("\n")
        result['저'] = author
#         print(author)
    else:
        for name_by_role in item.select_one(".authPub.info_auth").get_text().split("/"):
            temp = name_by_role.split()
            name = " ".join(temp[:-1])
            role = temp[-1]
            result[role] = name
    
    author_result.append(result)    
df = pd.DataFrame(author_result)
df

            저    역    글   그림     글그림
0      스즈키 유이  이지수  NaN  NaN     NaN
1    신영준, 고영성  NaN  NaN  NaN     NaN
2         정규준  NaN  NaN  NaN     NaN
3          자청  NaN  NaN  NaN     NaN
4         조현선  NaN  NaN  NaN     NaN
5       앤디 위어  강동혁  NaN  NaN     NaN
6         최태성  NaN  NaN  NaN     NaN
7         이광수  NaN  NaN  NaN     NaN
8         최태성  NaN  NaN  NaN     NaN
9         한로로  NaN  NaN  NaN     NaN
10    토니 페르난도  강정선  NaN  NaN     NaN
11        ETS  NaN  NaN  NaN     NaN
12        양귀자  NaN  NaN  NaN     NaN
13        NaN  NaN  윤자영  노이신     NaN
14        박곰희  NaN  NaN  NaN     NaN
15        박민규  NaN  NaN  NaN     NaN
16        NaN  이기웅  NaN  NaN     노부미
17        ETS  NaN  NaN  NaN     NaN
18        NaN  김성래  NaN  NaN     지누시
19        NaN  NaN  NaN  NaN  엔도 타츠야
20  David Cho  NaN  NaN  NaN     NaN
21        나태주  NaN  NaN  NaN     NaN
22        성승현  NaN  NaN  NaN     NaN
23     헤르만 헤세  박병덕  NaN  NaN     NaN

# yes24 종합베스트 999권 자료 수집해서 csv 파일로 저장하기
* book_data/
* yes24_수집일_best.csv
* 수집일은 datetime에서 오늘 날짜 추출해서 파일명에 포함시키기

In [13]:
import os
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs
from myfunc import text_clean

In [16]:
from datetime import datetime
datetime.now()
now=datetime.now()
print(f"{now.year}/{now.month}/{now.day}")

2026/3/16

In [17]:
today=datetime.today()
print(today)

2026-03-16 15:38:25.681392

In [18]:
today = f"{today.year}{today.month:02d}{today.day:02d}"
today

'20260316'

In [19]:
dir_name="book_data"
if not os.path.exists(dir_name):
    os.mkdir(dir_name)

In [20]:
result={}

for num in range(1,43):
    print(f"{num}/{42}    수집중", end="\r")
    url="https://www.yes24.com/product/category/bestseller"
    payload = dict(categoryNumber="001", pageNumber=num, pageSize=24)
    r = requests.get(url, params = payload)
    soup = bs(r.content, "lxml")

    
    for item in soup.select("#yesBestList > li"):

        book_id=item.select_one(".gd_name")["href"].split("/")[-1]

        # 책 종류
        kind=text_clean(item.select_one(".gd_res").get_text())

        # 책 제목
        book_title=item.select_one(".gd_name").get_text()

        # 상세페이지 링크
        detail_link="https://www.yes24.com" + item.select_one(".gd_name")["href"]

        # 저자/역자
        author=item.select_one(".authPub.info_auth").get_text().replace("\n", "").replace("\r", "")

        # 출판사
        publisher=item.select_one(".authPub.info_pub").get_text()

        # 출간일
        pub_date=item.select_one(".authPub.info_date").get_text()

        # 가격
        book_price=int(item.select_one("div.info_row.info_price em.yes_b").get_text().replace(",",""))

        # 리뷰수
        n_reviews=int(item.select_one(".txC_blue").get_text().replace(",","")) if item.select_one(".txC_blue") != None else 0

        # 리뷰 평점
        rating=float(item.select_one(".rating_grade em.yes_b").get_text()) if item.select_one(".rating_grade em.yes_b") != None else 0

        keys=("book_id", "kind","book_title","detail_link","author","publisher","pub_date","book_price","n_reviews","rating")

        values=(book_id, kind,book_title,detail_link,author,publisher,pub_date,book_price,n_reviews,rating)

        for key,value in zip(keys, values):
            result.setdefault(key, []).append(value)
        
#         time.sleep(3)
        
dir_name="book_data"
if not os.path.exists(dir_name):
    os.mkdir(dir_name)

df=pd.DataFrame(result)
df

df.to_csv(f"./book_data/yes24_{now.year}.{now.month}.{now.day}_best.csv", encoding="utf-8-sig")

# yes24_수집일_best.csv 파일에서 상세링크만 가져와서 상세페이지에 방문하고 
* book_id
* 쪽수, 무게, 크기 (다 따로)
* 카테고리 분류 (묶어도 상관없음)
* yes_24 수집일_best_detail.csv

# 수집하기

In [21]:
import os
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs
from myfunc import text_clean

In [22]:
from datetime import datetime

In [23]:
today = datetime.today()
print(today)

2026-03-16 15:39:17.817235

In [24]:
today = f"{today.year}{today.month:02d}{today.day:02d}"
today

'20260316'

In [27]:
data = pd.read_csv("./book_data/yes24_20260316_best.csv")
detail_links = data['detail_link']
detail_links

FileNotFoundError: [Errno 2] No such file or directory: './book_data/yes24_20260316_best.csv'

In [ ]:
all_detail_info = []
for idx, url in enumerate(detail_links):
    print(f"{idx}/{len(detail_links)}   수집중", end="\r")
    r = requests.get(url)
    soup = bs(r.content, "lxml")
    
    book_info ={}
    
    # book_id
    book_id = url.split("/")[-1]
    book_info['book_id'] = book_id 
    
    # 쪽수, 무게, 크기
    for row in soup.select("tbody.b_size tr"):
        if "쪽수" in row.select_one("th").get_text():
            pummoc_info = row.select_one("td").get_text().split("|")
    
    print(pummoc_info)
    for item in pummoc_info:
        temp = item.strip()
        if temp[-1] == "쪽":
            book_info["페이지"] = temp
        elif temp[-1] == "g":
            book_info['무게'] = temp
        elif temp[-1] == "m":
            book_info['크기'] = temp

    #카테고리 분류
    category = soup.select_one("#infoset_goodsCate .yesAlertLi > li").get_text(strip=True).split(">")    
    book_info['카테고리'] = category
   
    all_detail_info.append(book_info)
    
#     time.sleep(3)

df2 = pd.DataFrame(all_detail_info)
df2

In [ ]:
df2 = pd.DataFrame(all_detail_info)

dir_name = "book_data"
if not os.path.exists(dir_name):
        os.mkdir(dir_name)
        print(f"{dir_name}을 생성했습니다.")        
        

df2.to_csv(f"./{dir_name}/yes24_{today}_best_detail.csv")
df2